apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-extra-scrape
  namespace: monitoring
data:
  extra-targets.yaml: |
    - job_name: demo-app
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - demo
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: (.+)
          replacement: ${1}:$1
