apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Default admin password: supk8s-admin
  # Generate with: htpasswd -nbBC 10 "" 'supk8s-admin' | tr -d ':\n' | sed 's/$2y/$2a/'
  admin.password: "$2a$10$oreCdg.4QS.Y6qsOGisbre9Y331UefxHzNcuROsj00/YAkcbNlH3."
  admin.passwordMtime: "2026-01-01T00:00:00Z"
