apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: supk8s
  source:
    # Change this to your fork URL
    repoURL: https://github.com/jmunozti/supk8s.git
    targetRevision: develop
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
